# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f36b15741159fd39c1fee7afccee4a7767f52a8d3fdeafbee06893047ae5e709288252a15e576d0803a46dbd132055b3bc15ccf11fe7cfb916d6fdd2d8a64888

test:
  secret_key_base: 83485d850b30830626e69f3a73ce16cc8b05900cffb3b03a490c88d31885bfdd6e84d2bf20ec4958d915860db8cf754fc617c37bb99d4cdaa670abd1b33a65dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
